[theme]
primaryColor = "#0f8b8d"
backgroundColor = "#f6f8fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#263238"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
